export const LOAD_STUDENTS_SUCCESS = 'LOAD_STUDENTS_SUCCESS';
export const LOAD_STUDENTS_FAILURE = 'LOAD_STUDENTS_FAILURE';
export const BLOCK_STATUS_SUCCESS = 'BLOCK_STATUS_SUCCESS';
export const BLOCK_STATUS_FAILURE = 'BLOCK_STATUS_FAILURE';
