export const ADD_COMPANY_SUCCESS = 'ADD_COMPANY_SUCCESS';
export const ADD_COMPANY_FAILURE = 'ADD_COMPANY_FAILURE';
export const FILTER_SEARCH_COMPANY_SUCCESS = 'FILTER_SEARCH_COMPANY_SUCCESS';
export const FILTER_SEARCH_COMPANY_FAILURE = 'FILTER_SEARCH_COMPANY_FAILURE';