export const LOAD_INDUSTRY_SUCCESS = 'LOAD_INDUSTRY_SUCCESS';
export const LOAD_INDUSTRY_FAILURE = 'LOAD_INDUSTRY_FAILURE';
export const ADD_INDUSTRY_SUCCESS = 'ADD_INDUSTRY_SUCCESS';
export const ADD_INDUSTRY_FAILURE = 'ADD_INDUSTRY_FAILURE';